name: work_audiobook_clone
description: A sophisticated language-learning player clone mimicking WorkAudiobook.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  ffmpeg_kit_flutter: ^5.1.0
  path_provider: ^2.1.1
  flutter_audio_waveforms: ^1.2.0
  provider: ^6.1.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
